name: CI & Deploy to Vercel

on:
  push:
    branches:
      - main # 本番デプロイ対象ブランチ

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # Node.jsセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12

      # 3. 依存関係をクリーンインストール
      - name: Install dependencies
        run: npm ci

      # 4. テスト実行
      - name: Run tests
        run: npm run test -- --ci --coverage

      # 5. ビルド
      - name: Build project
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_WORDS_API_KEY: ${{ secrets.NEXT_PUBLIC_WORDS_API_KEY }}
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}

      # 6. Vercel CLI インストール
      - name: Install Vercel CLI
        run: npm install -g vercel

      # 7. Vercelデプロイ（本番）
      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
